### PR TITLE
PR for Mod Compatibility with Public Gui Announcement

### PR DESCRIPTION
**Pull request by AbsolemJackdaw**
the PGA :
https://www.curseforge.com/minecraft/mc-mods/public-gui-announcement

The Wiki on how these JSON files work :
https://github.com/ArtixAllMighty/PublicGuiAnnouncement/wiki/Add-Mod-Compatibility

In this PR is contained one json file to add compatibility with the mod Public Gui Announcement.
I wanted to ship the compat at first with my mod, but it would be better if the author maintains it himself. (in case of path and name changes as well addition or removal from screens).

I hereby give you all files needed to add compatibility to my mod. There is nothing else left to do apart from merging the PR.

If you have any other question, I'd be happy to answer !

### CODE REVIEW

**Comment by Exopandora** [comment]
This will be merged under the following conditions
1. `world_handler.png` has been renamed to ~`worldhandler.png` to match the modid~ `public_gui_announcement.png` 
2. The username and the watch pointers have been removed from the image to make it applicable for user

**Comment by AbsolemJackdaw** [comment]
1. Why ? Can i rename it pga_compst_gui.png ? The name is just an indicator of whst the image contains. Wether or not it has the modid has in essence nothing to do with the underlaying way of how it works.
2. No problem ! Missed that detail

**Comment by Exopandora** [comment]
Regarding 1: I know it has nothing to do with the functionality but this mod uses `world_handler` nowhere. Just call it `public_gui_announcement.png` so everybody knows what its for.

**Comment by AbsolemJackdaw** [comment]
Changed the path to textures/gui/modsupport (for extra clarity)
and renamed the image file to ``wordhandler_gui_publicguiannouncement`` so its a bot more forward as well as including the full word 'worldhandler'

**Pull request merged**
